### ISSUE TITLE
速腾32线

### ISSUE THREAD

**Issue by yyqgood** [AFEICHINA/expend_lidar_camera_calib#1]
你好，我使用速腾32线激光雷达，相机为USB免驱，使用rosbag录制了/points_raw和/usb_cam/image_raw两个主题的包，
修改了floam_rsbpearl32.launch和laserProcessingNode.cpp文件，如图所示
![1](https://user-images.githubusercontent.com/34564480/141425303-973bd317-b9eb-482c-904c-c74e2740352b.png)
:
![2](https://user-images.githubusercontent.com/34564480/141425314-2cfd126b-7828-472e-88c8-dd241552818f.png)
执行：roslaunch floam floam_rsbpearl32.launch，如图所示：
![3](https://user-images.githubusercontent.com/34564480/141425353-fc3a95aa-5369-4a59-a84b-1f3a871d7eec.png)
请问我错过了什么？谢谢！期待你的回复！

**Comment by AFEICHINA** [comment]
> 你好，我使用速腾32线激光雷达，相机为USB免驱，使用rosbag录制了/points_raw和/usb_cam/image_raw两个主题的包， 修改了floam_rsbpearl32.launch和laserProcessingNode.cpp文件，如图所示 ![1](https://user-images.githubusercontent.com/34564480/141425303-973bd317-b9eb-482c-904c-c74e2740352b.png) : ![2](https://user-images.githubusercontent.com/34564480/141425314-2cfd126b-7828-472e-88c8-dd241552818f.png) 执行：roslaunch floam floam_rsbpearl32.launch，如图所示： ![3](https://user-images.githubusercontent.com/34564480/141425353-fc3a95aa-5369-4a59-a84b-1f3a871d7eec.png) 请问我错过了什么？谢谢！期待你的回复！

从终端报错的信息来看我想不到会是什么错误，你可否发一份你录制的rosbag给我看一下。我的邮箱80672451@qq.com

**Comment by AFEICHINA** [comment]
> > 你好，我使用速腾32线激光雷达，相机为USB免驱，使用rosbag录制了/points_raw和/usb_cam/image_raw两个主题的包， 修改了floam_rsbpearl32.launch和laserProcessingNode.cpp文件，如图所示 ![1](https://user-images.githubusercontent.com/34564480/141425303-973bd317-b9eb-482c-904c-c74e2740352b.png) : ![2](https://user-images.githubusercontent.com/34564480/141425314-2cfd126b-7828-472e-88c8-dd241552818f.png) 执行：roslaunch floam floam_rsbpearl32.launch，如图所示： ![3](https://user-images.githubusercontent.com/34564480/141425353-fc3a95aa-5369-4a59-a84b-1f3a871d7eec.png) 请问我错过了什么？谢谢！期待你的回复！
> 
> 从终端报错的信息来看我想不到会是什么错误，你可否发一份你录制的rosbag给我看一下。我的邮箱[80672451@qq.com](mailto:80672451@qq.com)

更新了代码，你可以试试

**Comment by yyqgood** [comment]
我尝试了下，请见图片，我认为效果还不错；剩下的误差我认为是：
![20211115-105000](https://user-images.githubusercontent.com/34564480/141714764-c7d81309-cd3b-4c97-9f44-88fb0a7a8310.png)
1. 我选取的场景还不够典型
2. 我在录包时可以来回更细节化
3. 我会再查看代码级别是否还有可优化的地方

很高兴和你的合作，谢谢！

**Comment by yyqgood** [comment]
对于速腾32线，我发现此文件：
expend_lidar_camera_calib/livox_camera_calib/config/config_indoor_velodyne16.yaml 下的超参数是否需要修改，你有什么建议？
期待你的回复，谢谢！

**Comment by AFEICHINA** [comment]
> 对于速腾32线，我发现此文件： expend_lidar_camera_calib/livox_camera_calib/config/config_indoor_velodyne16.yaml 下的超参数是否需要修改，你有什么建议？ 期待你的回复，谢谢！

个人觉得场景的选择(是否能够提取出有效的线)，相机的内参准确度和slam后的点云精度更为重要，其他的超参数微调过对标定结果没有太大的影响。

**Comment by pedestrain123** [comment]
> 我尝试了下，请见图片，我认为效果还不错；剩下的误差我认为是： ![20211115-105000](https://user-images.githubusercontent.com/34564480/141714764-c7d81309-cd3b-4c97-9f44-88fb0a7a8310.png)
> 
> 1. 我选取的场景还不够典型
> 2. 我在录包时可以来回更细节化
> 3. 我会再查看代码级别是否还有可优化的地方
> 
> 很高兴和你的合作，谢谢！

@yyqgood 你好，请问你这是点云目标检测标注工具sustech吗?图像的3d检测框是通过画雷达检测框和外参投影映射到图像中形成三维框的吗？

**Comment by pedestrain123** [comment]
@yyqgood 你好，请问你这是点云目标检测标注工具sustech吗?图像的3d检测框是通过画雷达检测框和外参投影映射到图像中形成三维框的吗？
