### ISSUE TITLE
我在进行第二步是出现问题， process has died

### ISSUE THREAD

**Issue by fjg286823** [AFEICHINA/expend_lidar_camera_calib#10]
我已经阅读了所有的issue，但是没找到我的问题所在。我的雷达是速腾32线，在录制好相机/Daheng_image和雷达/velodyne_points的rosbag之后，修改floam_rslidar32.launch，成功运行了第一步，但是在显示过程中/map的点云无法显示，得到了一个map_.pcd；
我看issue中有人遇到了同样的问题，但是好像得到的map_.pcd是正确的，我也就没在意。在修改了两个yaml文件后，我运行calib_indoor_velodyne16.launch（也已经修改了bag和map_.pcd的位置）但是直接报错了

**Comment by AFEICHINA** [comment]
系统版本需要是 ubuntu 18.04

**Comment by fjg286823** [comment]
感谢您的回复，20.04是不行的吗



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月04日 21:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

系统版本需要是 ubuntu 18.04

**Comment by AFEICHINA** [comment]
> 感谢您的回复，20.04是不行的吗
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年05月04日 21:21 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) | 系统版本需要是 ubuntu 18.04 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

没调试过这个系统的版本。之前有人测试过20.04，有同样的的crash问题，用18.04就正常。

**Comment by fjg286823** [comment]
好的感谢您的回复！我计划用您这个第一步得到的pcd再结合原来的代码里提供的一个multi scenes calibration来尝试一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月04日 21:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

感谢您的回复，20.04是不行的吗
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年05月04日 21:21 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) | 系统版本需要是 ubuntu 18.04 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

没调试过这个系统的版本。之前有人测试过20.04，有同样的的crash问题，用18.04就正常。

**Comment by fjg286823** [comment]
我今天重新安装了ubuntu18，运行了这个程序，成功运行了，但是没有出现您程序运行完最后的点云被赋色的效果，是在rviz里add topic rgb_cloud吗,我添加这个话题也没有点云显示。雷达的fov比相机的fov大很多，我需要对map_.pcd进行一个处理来与相机fov进行匹配吗

**Comment by AFEICHINA** [comment]
> 我今天重新安装了ubuntu18，运行了这个程序，成功运行了，但是没有出现您程序运行完最后的点云被赋色的效果，是在rviz里add topic rgb_cloud吗,我添加这个话题也没有点云显示。雷达的fov比相机的fov大很多，我需要对map_.pcd进行一个处理来与相机fov进行匹配吗

rviz 窗口按住 space 空格好像是重新发送一次赋色点云。可以用CC处理下点云，把那块扣出来，效果会好点。

**Comment by fjg286823** [comment]
感谢您的回复，我去尝试一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月07日 23:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

Closed #10 as completed.

**Comment by Chatoyant19** [comment]
我用的是ubuntu20.04,定位到问题出在pcl setInputCloud 或者filter这一块，最终通过通过修改CMakeLists.txt解决了问题

**Comment by fjg286823** [comment]
谢谢你的回复，我通过安装ubuntu18解决了那个问题，但是还是想看看你的cmakelist.txt是如何修改的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月02日 15:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

我用的是ubuntu20.04,定位到问题出在pcl setInputCloud 或者filter这一块，最终通过通过修改CMakeLists.txt解决了问题

**Comment by Chatoyant19** [comment]
首先定位到是pcl filter这个函数导致的process has died, 然后google搜了一下，貌似pcl导致同样问题的还挺多的，然后在相应的CMakeLists.txt里面加了一个"set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")"就好了。

**Comment by fjg286823** [comment]
感谢你的回复！我去尝试一下



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月05日 11:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

首先定位到是pcl filter这个函数导致的process has died, 然后google搜了一下，貌似pcl导致同样问题的还挺多的，然后在相应的CMakeLists.txt里面加了一个"set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")"就好了。

**Comment by Chatoyant19** [comment]
你好，请问你有标定成吗？自己的机械lidar

**Comment by fjg286823** [comment]
标定成功了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月06日 15:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

你好，请问你有标定成吗？自己的机械lidar

**Comment by Chatoyant19** [comment]
方便加个联系方式，请教一下吗？我这边rough calib的结果看起来还是比较正常的，在最后优化的时候，突然跳变往完全错误的方向优化，我估计应该是lidar的边缘提取的不好导致的。

**Comment by fjg286823** [comment]
fjg19965457909微信



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月06日 15:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

方便加个联系方式，请教一下吗？我这边rough calib的结果看起来还是比较正常的，在最后优化的时候，突然跳变往完全错误的方向优化，我估计应该是lidar的边缘提取的不好导致的。

**Comment by Chatoyant19** [comment]
感谢你的回复，我的问题找到并且解决了，因为用的是鱼眼相机，在优化的时候点云会往完全错误的方向调整（即使已经确保投影模型部分已经修改还是不能直接输入鱼眼模型的原图像），先去畸变输入针孔图像，标定算法能往正确的方向优化。不过，我在另一个同是鱼眼相机但是焦距比较小的相机上的测试效果不太理想，看起来像是特征集中在上部分，并且只有比较少的横向约束，不知道您是否有些经验？

**Comment by AFEICHINA** [comment]
> 感谢你的回复，我的问题找到并且解决了，因为用的是鱼眼相机，在优化的时候点云会往完全错误的方向调整（即使已经确保投影模型部分已经修改还是不能直接输入鱼眼模型的原图像），先去畸变输入针孔图像，标定算法能往正确的方向优化。不过，我在另一个同是鱼眼相机但是焦距比较小的相机上的测试效果不太理想，看起来像是特征集中在上部分，并且只有比较少的横向约束，不知道您是否有些经验？

标定的算法要求输入的是未去畸变的图像，鱼眼相机模型需要修改投影模型和ceres优化仿函数中的相机投影模型。

**Comment by fjg286823** [comment]
抱歉，我可能帮不到你，你试试拍的场景里多一些物体（注意不要出现大平面物体，我当时在大平面物体上几乎检测不到特征）试试，



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月28日 21:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

感谢你的回复，我的问题找到并且解决了，因为用的是鱼眼相机，在优化的时候点云会往完全错误的方向调整（即使已经确保投影模型部分已经修改还是不能直接输入鱼眼模型的原图像），先去畸变输入针孔图像，标定算法能往正确的方向优化。不过，我在另一个同是鱼眼相机但是焦距比较小的相机上的测试效果不太理想，看起来像是特征集中在上部分，并且只有比较少的横向约束，不知道您是否有些经验？

标定的算法要求输入的是未去畸变的图像，鱼眼相机模型需要修改投影模型和ceres优化仿函数中的相机投影模型。

**Comment by Chatoyant19** [comment]
> 

和相机投影相关的部分都有修改的，和https://github.com/hku-mars/livox_camera_calib/issues/37现象一致，具体的原因还不明确，目前就是通过先去畸变再输入到算法里面，也能去标定。你有标定过鱼眼相机吗？是通过直接修改投影模型部分成功的吗

**Comment by Chatoyant19** [comment]
> 抱歉，我可能帮不到你，你试试拍的场景里多一些物体（注意不要出现大平面物体，我当时在大平面物体上几乎检测不到特征）试试，
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年06月28日 21:47 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) | 感谢你的回复，我的问题找到并且解决了，因为用的是鱼眼相机，在优化的时候点云会往完全错误的方向调整（即使已经确保投影模型部分已经修改还是不能直接输入鱼眼模型的原图像），先去畸变输入针孔图像，标定算法能往正确的方向优化。不过，我在另一个同是鱼眼相机但是焦距比较小的相机上的测试效果不太理想，看起来像是特征集中在上部分，并且只有比较少的横向约束，不知道您是否有些经验？ 标定的算法要求输入的是未去畸变的图像，鱼眼相机模型需要修改投影模型和ceres优化仿函数中的相机投影模型。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

是的，就是因为提到的特征约束不够，我在地下车库找到两边都是方形的柱子的场景，标定成功了。

**Comment by Chatoyant19** [comment]
> > 感谢你的回复，我的问题找到并且解决了，因为用的是鱼眼相机，在优化的时候点云会往完全错误的方向调整（即使已经确保投影模型部分已经修改还是不能直接输入鱼眼模型的原图像），先去畸变输入针孔图像，标定算法能往正确的方向优化。不过，我在另一个同是鱼眼相机但是焦距比较小的相机上的测试效果不太理想，看起来像是特征集中在上部分，并且只有比较少的横向约束，不知道您是否有些经验？
> 
> 标定的算法要求输入的是未去畸变的图像，鱼眼相机模型需要修改投影模型和ceres优化仿函数中的相机投影模型。

其中和相机投影相关的部分都有修改的，和 https://github.com/hku-mars/livox_camera_calib/issues/37 现象一致，目前先把图像去畸变再输入到标定算法中也是能有效校正的。请问你有标定过鱼眼相机吗？是通过直接修改投影模型成功的吗？

**Comment by fjg286823** [comment]
恭喜你标定成功。
很抱歉，我没有做过鱼眼相机标定。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月29日 14:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) |

抱歉，我可能帮不到你，你试试拍的场景里多一些物体（注意不要出现大平面物体，我当时在大平面物体上几乎检测不到特征）试试，
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年06月28日 21:47 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [AFEICHINA/extended_lidar_camera_calib] 我在进行第二步是出现问题， process has died (Issue #10) | 感谢你的回复，我的问题找到并且解决了，因为用的是鱼眼相机，在优化的时候点云会往完全错误的方向调整（即使已经确保投影模型部分已经修改还是不能直接输入鱼眼模型的原图像），先去畸变输入针孔图像，标定算法能往正确的方向优化。不过，我在另一个同是鱼眼相机但是焦距比较小的相机上的测试效果不太理想，看起来像是特征集中在上部分，并且只有比较少的横向约束，不知道您是否有些经验？ 标定的算法要求输入的是未去畸变的图像，鱼眼相机模型需要修改投影模型和ceres优化仿函数中的相机投影模型。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

是的，就是因为提到的特征约束不够，我在地下车库找到两边都是方形的柱子的场景，标定成功了。
