### ISSUE TITLE
关于数据准备问题

### ISSUE THREAD

**Issue by yulongg1** [AFEICHINA/expend_lidar_camera_calib#11]
你好，我想请问一下，准备数据的时候是各个角度和方向的移动都要有吗？比如传感器在小车上可能只有x，y和yaw方向的移动，这样可以吗？再就是有无实验数据提供一下呢？谢谢！

**Comment by AFEICHINA** [comment]
> 你好，我想请问一下，准备数据的时候是各个角度和方向的移动都要有吗？比如传感器在小车上可能只有x，y和yaw方向的移动，这样可以吗？再就是有无实验数据提供一下呢？谢谢！

这里移动的目的是为了生成稠密的地图，只要移动可以生成合适的地图就可以。
