### ISSUE TITLE
How can I solve the problem about "LZ4_streamDecode_t"?

### ISSUE THREAD

**Issue by Duke-Rodriguez-Rudolph** [AFEICHINA/expend_lidar_camera_calib#2]
Hello! When I run the command of "catkin_make", there is a problem about "LZ4_streamDecode_t". The detailed information is followed.
error: conflicting declaration ‘typedef struct LZ4_streamDecode_t LZ4_streamDecode_t’
 edef struct { unsigned long long table[LZ4_STREAMDECODESIZE_U64]; } LZ4_streamDecode_t;
                                                                     ^~~~~~~~~~~~~~~~~~

**Comment by AFEICHINA** [comment]
Hi, you could read this issue :)
https://github.com/ethz-asl/lidar_align/issues/16

**Comment by Duke-Rodriguez-Rudolph** [comment]
Thank you! I have solved it.
