### ISSUE TITLE
您好，原论文中是静止录制数据，最后选取图像是一定的，如果通过slam移动雷达获取稠密点云后，最后标定的pcd和图像怎么获取，非常感谢您

### ISSUE THREAD

**Issue by af-doom** [AFEICHINA/expend_lidar_camera_calib#4]

**Comment by AFEICHINA** [comment]
> _No description provided._

你好，雷达在做slam的时候，会以第一帧雷达点的坐标系原点做为map坐标系原点。所以使用第一帧雷达对应时刻的图像就可以做后续的标定。如果没有做camera和LiDAR同步的话，可以先静止装置一段时间，然后再做slam运动。

**Comment by af-doom** [comment]
> 
非常感谢您这么快的回复，就是我在静止时录制的bag包取一张图像就行吗

**Comment by af-doom** [comment]
> > _No description provided._
> 
> 你好，雷达在做slam的时候，会以第一帧雷达点的坐标系原点做为map坐标系原点。所以使用第一帧雷达对应时刻的图像就可以做后续的标定。如果没有做camera和LiDAR同步的话，可以先静止装置一段时间，然后再做slam运动。

您好，非常感谢您对小白的回复，就是静止一段时间后，移动雷达做slam,移动的时候是缓慢左右平移吗，Z轴需要运动吗，或者怎么采集数据，感谢您的工作和回复。

**Comment by AFEICHINA** [comment]
> > > _No description provided._
> > 
> > 
> > 你好，雷达在做slam的时候，会以第一帧雷达点的坐标系原点做为map坐标系原点。所以使用第一帧雷达对应时刻的图像就可以做后续的标定。如果没有做camera和LiDAR同步的话，可以先静止装置一段时间，然后再做slam运动。
> 
> 您好，非常感谢您对小白的回复，就是静止一段时间后，移动雷达做slam,移动的时候是缓慢左右平移吗，Z轴需要运动吗，或者怎么采集数据，感谢您的工作和回复。

1.生成地图需要均匀，密度足够，所以需要缓慢朝着各个地方移动。
2.静止时候取一张图片即可。

**Comment by pedestrain123** [comment]
@AFEICHINA 您好，请问只需一组图片和点云pcd就可以完成标定吗？还是说需要多组图像和点云pcd ？

**Comment by pedestrain123** [comment]
@AFEICHINA 您好，请问只需一组图片和点云pcd就可以完成标定吗？还是说需要多组图像和点云pcd ？

**Comment by AFEICHINA** [comment]
> @AFEICHINA 您好，请问只需一组图片和点云pcd就可以完成标定吗？还是说需要多组图像和点云pcd ？

静止时刻一张图片和累计起来的点云地图就可以，具体算法可以参考原论文。
