### ISSUE TITLE
Bpearl support

### ISSUE THREAD

**Issue by kakghiroshi** [AFEICHINA/expend_lidar_camera_calib#5]
Hi!Thanks for your great work!
I'm using RS-Bpearl as you do.But here is the problem:I launch the floam_rsbpearl32.launch and play my bag.But nothing happened,it seems like the algorithm doesn't get my data.Is anything needed to modify？
Your prompt reply will be appreciate!

**Comment by AFEICHINA** [comment]
Hi!
Yes, The rsbpearl lidar driver I use  in the project is modified by my own.  So you can rewrite the function convertMyLidarToPCLPointCloud to get the lidar cloud.  Besides, make sure the lidar ros topic is correct.

**Comment by kakghiroshi** [comment]
Thanks for your reply!
I took a cursory look at the function and have no idea where to change.
Could you please give me a light on how to rewrite it ?

**Comment by kakghiroshi** [comment]
After checking the floam_rsbpearl32.launch，change https://github.com/AFEICHINA/extended_lidar_camera_calib/blob/dcb4a852be780104f8f52edf6e684fb0d83076dc/floam/launch/floam_rsbpearl32.launch#L34
to `<remap from="/velodyne_points" to="/rslidar_points" /> `works.
