### ISSUE TITLE
Data collecting

### ISSUE THREAD

**Issue by farhad-dalirani** [AFEICHINA/expend_lidar_camera_calib#6]
Hi, 
Can you explain how to collect data?

I should collect data for both camera and Lidar when moving?
If I need to just take a picture, where to put it? and how can I do it?
Which direction should I move?

Thank you,

**Comment by AFEICHINA** [comment]
Hi, 
sorry for the late reply.  

1.the picture is collected automatically in step 2.
2.make sure the lidar and camera are synchronized.
3.the origin algorithm is designed for livox lidar,  which can get dense pointcloud at stationary scenery. For spinning lidar, we have to move the lidar for dense map result. Therefore, you should move the sensor in all directions to get a dense and even map of the pointcloud.

**Comment by farhad-dalirani** [comment]
Thank you for your getting back to me.

What do you mean by synchronized? Do you mean exact synchronization? If you could elevate it a little more it would be great. 

Because in my setting I collect camera and lidar data while moving and there is no synchronization between them. I use ROS time for both sensors' message timestamps.

**Comment by farhad-dalirani** [comment]
Ros time stamps was enough. Thank you for answers.

**Comment by zayedrmdn** [comment]
Hi @AFEICHINA, I'm using a 32-channel RSLidar, and the point cloud appears dense enough in the screenshot. Do I still need to move around while recording?
![image](https://github.com/user-attachments/assets/32d972d4-b6fe-400a-b10d-68c2311fc0fc)

**Comment by AFEICHINA** [comment]
> Hi @AFEICHINA, I'm using a 32-channel RSLidar, and the point cloud appears dense enough in the screenshot. Do I still need to move around while recording? ![image](https://private-user-images.githubusercontent.com/77555532/358512280-32d972d4-b6fe-400a-b10d-68c2311fc0fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDAxNjYsIm5iZiI6MTcyNDEzOTg2NiwicGF0aCI6Ii83NzU1NTUzMi8zNTg1MTIyODAtMzJkOTcyZDQtYjZmZS00MDBhLWIxMGQtNjhjMjMxMWZjMGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA3NDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4Mzk4ZDQyNjM0ZmI4MWNkYjIxNjY5MWNmYjBlYjg2NTFiMDk0YWI0YWU1ZTlhZTEyY2NlOTBkODMxNWNiNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KVyKv11wY7t5mgKqEArs8PCKbFFNlJLrAXswHj26q2M)

Yes, the pointclouds map are not enough when lidar stay at stationary scenery.
