### ISSUE TITLE
Problem in running code

### ISSUE THREAD

**Issue by farhad-dalirani** [AFEICHINA/expend_lidar_camera_calib#7]
Hello,  

I collected a rosbag with my camera and lidar. I move both sensors with constant relative position to each other for several second to collect data. Then I save rosbag and close sensors.

1) I call floam with this line: `roslaunch floam floam_velodyne1.launch`
Before calling it, I modified rosbag path in the launch file.

When Rviz pop up, it show no point on the rviz. However, when I open save map with pcl viewer, it seems ok and proper.

2) For calibration I call `roslaunch livox_camera_calib calib_indoor_velodyne16.launch`

Before, calling it, I changed my rosbag file path and camera and lidar topic names in these two config files: `'/config/camera_velodyne16.yaml' '/config/config_indoor_velodyne16.yaml '
`
I recieve an Error: process has died.

**Comment by AFEICHINA** [comment]
Hi, please check the lidar and camera topic name in config_indoor_velodyne16.yaml.

**Comment by farhad-dalirani** [comment]
Again thank you for your reply.
In the config_indoor_velodyne16.yaml we have these:

```
# Topic name in rosbag
PointCloudTopic: "/velodyne_points"
ImageTopic: "/camera_0/image"

# Lidar Data type(custom msg or pointcloud2)
Data.custom_msg:  0
# Initial extrinsic (usually provided by hand measurement or cad design)
```

I use Velodyne 16, so I do not need to change the lidar topic name. However my camera outputs `lumenera/1/image_raw`, so do I need to replace `/camera_0/image` with it?

Can I send my rosbag to you?

**Comment by AFEICHINA** [comment]
> 

Yes, replacing the topic name by your sensor name. ROS time for both sensors' message should be fine. if you still recieve errors  after changing topic names,  please send bag to my email.

**Comment by farhad-dalirani** [comment]
Hello sir, 
I sent an email to your mail address that is mentioned in your Github page.
Best,

**Comment by AFEICHINA** [comment]
> Hello sir, I sent an email to your mail address that is mentioned in your Github page. Best,

Hello, I download your bags and test it on my computer,There are my results.
![image](https://user-images.githubusercontent.com/26079089/224601790-e82d1919-c47f-488b-a904-c51894f9971f.png)
![image](https://user-images.githubusercontent.com/26079089/224601848-a8c8f443-9ccc-4cdb-b1d1-145124470428.png)
![image](https://user-images.githubusercontent.com/26079089/224602001-ac9cc99e-9b0d-40d6-b140-b5ba62663a8f.png)

My modification steps are
1.modify the bag path in floam_velodyne1.launch to generat dense map.
![image](https://user-images.githubusercontent.com/26079089/224602886-ac8d4c29-e6ee-4bd0-bad0-d18add9742dd.png)

2. modify the camera config  in camea_velodyne16.yaml.
![image](https://user-images.githubusercontent.com/26079089/224602838-429285ee-ad9a-466c-b630-b56854e458e3.png)

3. modify the imagetopic in config_indoor_velodyne16.yaml
![image](https://user-images.githubusercontent.com/26079089/224602783-9c44426c-2aee-4790-8ac0-4a6007903241.png)

4. modify the launch config in calib_indoor_velodyne16.launch
![image](https://user-images.githubusercontent.com/26079089/224605571-1c9b9cd7-2c46-4288-b60c-57d2752de2c2.png)


then 
roslaunch floam floam_velodyne1.launch

roslaunch livox_camera_calib calib_indoor_velodyne16.launch

Best Regards.

**Comment by farhad-dalirani** [comment]
Thank you sir for all your help. The problem was my setup. So, I close the issue.
