### ISSUE TITLE
record a bag or capture a picture and pointcloud?

### ISSUE THREAD

**Issue by fjg286823** [AFEICHINA/expend_lidar_camera_calib#8]
After running floam,Do I record a bag(map topic and image topic) or capture a  picture and point cloud with the same timestamp?

**Comment by AFEICHINA** [comment]
you can refer this [issue](https://github.com/AFEICHINA/extended_lidar_camera_calib/issues/4)

**Comment by fjg286823** [comment]
Thank you  very much.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/03/2023 23:00 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [AFEICHINA/extended_lidar_camera_calib] record a bag or capture a picture and pointcloud? (Issue #8) |

you can refer this issueissue 4
