### ISSUE TITLE
which launch file should i roslaunch?

### ISSUE THREAD

**Issue by fjg286823** [AFEICHINA/expend_lidar_camera_calib#9]
i roslanch floam_rslidar32.launch,but i can't found corresponding launch file. i only found  calib_indoor_rsbpearl32.launch. is it same that roslaunch this file?

**Comment by AFEICHINA** [comment]
you may modify the topics in launch files to satisfy your bag. For more details, referring this [issue](https://github.com/AFEICHINA/extended_lidar_camera_calib/issues/7)

**Comment by fjg286823** [comment]
OK,thank you



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/03/2023 23:02 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [AFEICHINA/extended_lidar_camera_calib] which launch file should i roslaunch? (Issue #9) |

you may modify the topics in launch files to satisfy your bag
